# Generated by Django 3.2.4 on 2021-06-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210608_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='Freshman', max_length=20),
        ),
    ]
