# Generated by Django 3.2.4 on 2021-06-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210610_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollee',
            old_name='courseId',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='enrollee',
            old_name='studentId',
            new_name='student_id',
        ),
    ]
